### ISSUE TITLE
Fix conditional installation of future-fstrings

### ISSUE THREAD

**Issue by hectcastro** [azavea/django-ecsmanage#13]
When encoding cookies are present, they fail if the referenced encoder is not. During the installation process, we need to conditionally strip the encoding cookies for versions of Python with fstring support. In versions that don't support it, we need to install `future-fstrings` and keep the encoding cookie intact.

> You need to make both the existence of that line and the installation of the package depend on the python version, e.g. by modifying your setup.py to strip that line if running under Python 3.6+

**Comment by flying-sheep** [comment]
> we need to conditionally strip the encoding cookies for versions of Python with fstring support.

Or add them for the versions without. That way ’round would have the added advantage that you can’t forget to add the lines to any new source files.
