### ISSUE TITLE
Drop support for Python 3.5

### ISSUE THREAD

**Issue by coalkettler** [azavea/django-ecsmanage#18]
We can drop support for Python 3.5 after [2020-09-13](https://devguide.python.org/#status-of-python-branches). When we do so we should uninstall `future-fstrings` since f-strings are supported in Python 3.6+.

For CI, we will no longer need to include `future-fstrings` in the `tox` `lint` environment as a dependency either and we should lint using Python 3.6.

**Comment by hectcastro** [comment]
I believe that closing this will take care of https://github.com/azavea/django-ecsmanage/issues/13 too.
